# The URL the site will be built for
base_url = "https://cfmeyers.com/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

title = "Tech Blog"
description = "Data engineering and other things"
default_language = "en"
theme = "serene"
output_dir = "public"
minify_html = true
build_search_index = true
generate_feeds = false
feed_filenames = ["feed.xml"]
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
extra_syntaxes = []
highlight_theme = "one-dark" # Code highlight theme, choose one at https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
name = "Collin Meyers"                         # Your name
id = "cfmeyers"                           # Your id / username / handle
bio = "Data Engineer"                          # Your bio
avatar = "img/avatar.webp"            # Your avatar
links = [                             # Your links
    { name = "GitHub", icon = "github", url = "https://github.com/cfmeyers" },
    { name = "Twitter", icon = "twitter", url = "https://twitter.com/cfmeyers" },
    { name = "Email", icon = "email", url = "mailto:example@example.com" },
]

nav_separator = "::"

display_id = true                     # Display your id on homepage
projects_page = true                  # Display projects page
blog_categorized = true               # Whether to categorize blog posts
blur_effect = true                    # Whether to turn on blur effect on navigation bar

toc = true                            # Whether to show Table-Of-Contents by default
comment = false                       # Whether to show giscus comment section by default, see https://giscus.app for more info

outdate_alert = false                 # Whether to show outdate alert by default
outdate_alert_days = 120              # How many days will a post be outdated by default
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

footer_copyright = "© 2025 Collin Meyers"
footer_credits = true                 # Whether to show "Powered by Zola and Serene" in footer
force_theme = false

sections = [
  { name = "blog", path = "/blog", is_external = false },
  { name = "github", path = "https://github.com/cfmeyers", is_external = true },
]
blog_section_path = "/blog"
back_link_text = "Back" # Text of the back button
reaction = false
not_found_error_text = "404 Not Found"
not_found_recover_text = "« back to home »"
